insert into CURRENCY_EXCHANGE (CONVERSION_MULTIPLE ,ID ,CURRENCY_FROM ,CURRENCY_TO, ENVIRONMENT ) values('50','101','USD','INR','');
insert into CURRENCY_EXCHANGE (CONVERSION_MULTIPLE ,ID ,CURRENCY_FROM ,CURRENCY_TO, ENVIRONMENT ) values('60','102','AUD','INR','');
insert into CURRENCY_EXCHANGE (CONVERSION_MULTIPLE ,ID ,CURRENCY_FROM ,CURRENCY_TO, ENVIRONMENT ) values('70','103','EUR','INR','');